### ISSUE TITLE
Tracker打出一些日志，让我们能看到效果来

### ISSUE THREAD

**Issue by xiaods** [Dataman-Cloud/p2pull#12]

**Comment by xiaods** [comment]
```
2015/09/19 17:36:21 dealing with https://index.alauda.cn/v2/
2015/09/19 17:36:21 [ fce580bf47744e6e6feaf8441af8c2520dd60849 ] Tracker: [], Comment: , InfoHash: 2c8aab2eebb02d652a61b249f5b7d96c1c849a12, Encoding: , Private: 0
2015/09/19 17:36:21 http: panic serving 10.3.11.3:39588: runtime error: invalid memory address or nil pointer dereference
goroutine 14 [running]:
net/http.func·011()
    /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/jackpal/Taipei-Torrent/torrent.(*TorrentSession).load(0xc208068200, 0x0, 0x0)
    /root/go/src/github.com/jackpal/Taipei-Torrent/torrent/torrent.go:234 +0x64b
github.com/jackpal/Taipei-Torrent/torrent.NewTorrentSession(0xc20805c120, 0xc208056880, 0x35, 0x1e6c, 0x0, 0x0, 0x0)
    /root/go/src/github.com/jackpal/Taipei-Torrent/torrent/torrent.go:187 +0x886
main.(*Tracker).handleSafely(0xc20805c1b0, 0x7f66ee9856c8, 0xc2080480a0, 0xc20801e5e0, 0x1b, 0x0, 0x0)
    /root/p2pull/bay/tracker/tracker.go:125 +0x1de
main.(*Tracker).handle(0xc20805c1b0, 0x7f66ee9856c8, 0xc2080480a0, 0xc2080345b0)
    /root/p2pull/bay/tracker/tracker.go:168 +0x4c7
main.*Tracker.(main.handle)·fm(0x7f66ee9856c8, 0xc2080480a0, 0xc2080345b0)
    /root/p2pull/bay/tracker/tracker.go:75 +0x45
net/http.HandlerFunc.ServeHTTP(0xc20802ab10, 0x7f66ee9856c8, 0xc2080480a0, 0xc2080345b0)
    /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20803d350, 0x7f66ee9856c8, 0xc2080480a0, 0xc2080345b0)
    /usr/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc208046300, 0x7f66ee9856c8, 0xc2080480a0, 0xc2080345b0)
    /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208048320)
    /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1751 +0x35e
2015/09/19 17:36:21 dealing with https://index.alauda.cn/v1/_ping
2015/09/19 17:36:21 [ 7de645b1794a139560a6700c5b58be7335b01e82 ] Tracker: [], Comment: , InfoHash: cc60a2f5c8dc385a22df48c9885bec260a40813c, Encoding: , Private: 0
2015/09/19 17:36:21 http: panic serving 10.3.11.3:39590: runtime error: invalid memory address or nil pointer dereference
goroutine 15 [running]:
net/http.func·011()
    /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/jackpal/Taipei-Torrent/torrent.(*TorrentSession).load(0xc208068400, 0x0, 0x0)
    /root/go/src/github.com/jackpal/Taipei-Torrent/torrent/torrent.go:234 +0x64b
github.com/jackpal/Taipei-Torrent/torrent.NewTorrentSession(0xc20805c120, 0xc208056b80, 0x35, 0x1e6c, 0x0, 0x0, 0x0)
    /root/go/src/github.com/jackpal/Taipei-Torrent/torrent/torrent.go:187 +0x886
main.(*Tracker).handleSafely(0xc20805c1b0, 0x7f66ee9856c8, 0xc208048460, 0xc20801f2c0, 0x20, 0x0, 0x0)
    /root/p2pull/bay/tracker/tracker.go:125 +0x1de
main.(*Tracker).handle(0xc20805c1b0, 0x7f66ee9856c8, 0xc208048460, 0xc208034ea0)
    /root/p2pull/bay/tracker/tracker.go:168 +0x4c7
main.*Tracker.(main.handle)·fm(0x7f66ee9856c8, 0xc208048460, 0xc208034ea0)
    /root/p2pull/bay/tracker/tracker.go:75 +0x45
net/http.HandlerFunc.ServeHTTP(0xc20802ab10, 0x7f66ee9856c8, 0xc208048460, 0xc208034ea0)
    /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20803d350, 0x7f66ee9856c8, 0xc208048460, 0xc208034ea0)
    /usr/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc208046300, 0x7f66ee9856c8, 0xc208048460, 0xc208034ea0)
    /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2080483c0)
    /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1751 +0x35e
2015/09/19 17:36:21 dealing with https://index.alauda.cn/v1/_ping
2015/09/19 17:36:21 waiting for current download to finish
2015/09/19 17:36:21 dealing with https://index.alauda.cn/v1/_ping
2015/09/19 17:36:21 waiting for current download to finish
```

**Comment by xiaods** [comment]
fix it
